add a command to install aws CLI

diff --git a/.gitpod.yml b/.gitpod.yml
--- a/.gitpod.yml
+++ b/.gitpod.yml
@@ -4,12 +4,23 @@ tasks:
       AWS_CLI_AUTO_PROMPT: on-partial
     command: |
       cd /workspace
-      if ! test -x "$(command -v aws)"; then
-        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
-        unzip awscliv2.zip
-        sudo ./aws/install
+      if ! command -v aws &> /dev/null
+      then
+          if [ -f awscliv2.zip ]
+          then
+              echo "AWS CLI installation package already downloaded."
+          else
+              echo "AWS CLI is not installed and the installation package is not found. Downloading it now..."
+              curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+          fi
+          echo "Installing AWS CLI..."
+          unzip awscliv2.zip
+          sudo ./aws/install
+          rm -rf awscliv2.zip aws
+          echo "AWS CLI installation complete."
+      else
+          echo "AWS CLI is already installed."
       fi
-      cd $THEIA_WORKSPACE_ROOT
   - name: postgres
     command: |
       curl -fsSL https://www.postgresql.org/media/keys/ACCC4CF8.asc|sudo gpg --dearmor -o /etc/apt/trusted.gpg.d/postgresql.gpg
